### ISSUE TITLE
Why is the internal code of the program not in the internal package?

### ISSUE THREAD

**Issue by ChoKhoOu** [GalvinGao/gofiber-template#40]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/38033263/232234258-ac7e9e1d-3179-47b1-a345-9d4974ff18cd.png">

Like this，I think that if the code does not need to be exposed to the outside world, it should be placed in the internal

**Comment by GalvinGao** [comment]
Makes sense; gonna fix soon :D

**Comment by GalvinGao** [comment]
Fixed in 064562f526123a594906b22793d01bab34504351
